

/******************************************************************************
*
*  PROJECT:		R40 DISPATCHER / NOKIA TELECOMMUNICATIONS
*	
*  FILE:		MAP_NETS.H
*
*  PURPOSE:		MAP27 Network Layer Process
*
*  REMARKS:		
*
*  AUTHOR:		P. Kettunen
*
*  LAST UPDATE:		13.3.1993
*
*
*		KUUMIC OY (C) 1993
*
******************************************************************************/



void PROCESS_network( void );
void NET_init( void );

/*---------------------------------------------------------------------------*/



