

/******************************************************************************
*
*  PROJECT:		R40 DISPATCHER / NOKIA TELECOMMUNICATIONS
*	
*  FILE:		MAP_SYS.H
*
*  PURPOSE:		MAP27 System
*
*  REMARKS:		
*
*  AUTHOR:		P. Kettunen
*
*  LAST UPDATE:		21.4.1993
*
*
*		KUUMIC OY (C) 1993
*
******************************************************************************/


void MAP_scheduler( void );
void MAP_init(void);
void InitSys (void);
void InitPorts();
void InitCom (void);

/*---------------------------------------------------------------------------*/



